Create a 5X2 random integer array and Prints its attributes • The shape of an array • Array dimensions • The length of each elements of an array in bytes

In [2]:
import numpy as np
a = np.random.randint(0,10,size=(5,2))
np.shape(a)

(5, 2)

In [3]:
a.ndim

2

In [4]:
a.nbytes

80

Create a 4X2 random integer array from a range between 10 to 20 such that the difference between each element is 2.

In [5]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

Create a 6X4 random integer array and print the following

In [6]:
b= np.random.randint(10,size=(6,4))
b

array([[8, 1, 9, 3],
       [4, 6, 4, 6],
       [6, 9, 7, 5],
       [1, 3, 7, 6],
       [3, 9, 9, 3],
       [3, 2, 4, 8]])

• The third column

In [7]:
b[:,2]

array([9, 4, 7, 7, 9, 4])

• Array of odd rows and even columns

In [8]:
b[[1,3,5]]

array([[4, 6, 4, 6],
       [1, 3, 7, 6],
       [3, 2, 4, 8]])

In [9]:
b[:,[1,2,]]

array([[1, 9],
       [6, 4],
       [9, 7],
       [3, 7],
       [9, 9],
       [2, 4]])

• Array of square of each element

In [10]:
np.square(b)

array([[64,  1, 81,  9],
       [16, 36, 16, 36],
       [36, 81, 49, 25],
       [ 1,  9, 49, 36],
       [ 9, 81, 81,  9],
       [ 9,  4, 16, 64]])

Split the array into two equal sub arrays

In [22]:
np.split(b,3)

[array([[8, 1, 9, 3],
        [4, 2, 4, 6]]), array([[6, 3, 7, 5],
        [1, 4, 7, 6]]), array([[3, 5, 9, 3],
        [3, 6, 4, 8]])]

• Sort the array by the second row

In [12]:
k= b[np.argsort(b[1, :])]
k

array([[8, 1, 9, 3],
       [6, 9, 7, 5],
       [4, 6, 4, 6],
       [1, 3, 7, 6]])

• Sort the array by the second column

In [13]:
z= b[np.argsort(b[:, 1])]
z

array([[8, 1, 9, 3],
       [3, 2, 4, 8],
       [1, 3, 7, 6],
       [4, 6, 4, 6],
       [6, 9, 7, 5],
       [3, 9, 9, 3]])

• Amax from axis 0 and Amin from axis 1

In [14]:
np.max(b,axis=0)

array([8, 9, 9, 8])

In [15]:
np.min(b,axis=0)

array([1, 1, 4, 3])

• Delete column 2 and insert [1,2,3,4,5,6] to column 2

In [16]:
np.delete(b,b[:,1])
b[:,1]= [1,2,3,4,5,6]
b

array([[8, 1, 9, 3],
       [4, 2, 4, 6],
       [6, 3, 7, 5],
       [1, 4, 7, 6],
       [3, 5, 9, 3],
       [3, 6, 4, 8]])

• Rotate by 90 degree

In [17]:
np.rot90(b)

array([[3, 6, 5, 6, 3, 8],
       [9, 4, 7, 7, 9, 4],
       [1, 2, 3, 4, 5, 6],
       [8, 4, 6, 1, 3, 3]])

• Print the most frequent value in the array

In [ ]:
b
print(np.bincount(b).argmax())

• Flatten the array to 1D

In [19]:
b.flatten()

array([8, 1, 9, 3, 4, 2, 4, 6, 6, 3, 7, 5, 1, 4, 7, 6, 3, 5, 9, 3, 3, 6,
       4, 8])

• Replace values less than 10 by a NAN.

In [ ]:
b[b < 10] = 5


 Summarize the array statistically (mean,mode,median, ¼ -quartile, ¾-quartile,max,min)

In [ ]:
np.mean(b)

In [ ]:
np.percentile(b, 0.75)

In [ ]:
np.percentile(b, 3.75)

In [ ]:
np.max(b)

In [ ]:
np.min(b)