<a href="https://colab.research.google.com/github/muga01/python_basics/blob/main/Exercise2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercise 2

In [ ]:
import numpy as np

#### 1. Create a null vector of size 20 but fill the tenth value with 1 (★☆☆)

maximum number of code lines allowed = `2` 

In [ ]:
x=np.empty(20) 
x[9]=1
x


array([4.68540293e-310, 1.73771270e+097, 9.82157975e+252, 8.89489936e+252,
       6.01346954e-154, 6.01347002e-154, 6.01347002e-154, 7.49877502e+247,
       6.96742172e+252, 1.00000000e+000, 1.19490107e+190, 5.08200698e+233,
       1.53336497e-094, 6.01347002e-154, 6.01347002e-154, 6.01347002e-154,
       1.88556770e+122, 4.96820036e+180, 6.80600993e+212, 8.73449626e-313])

#### 2. Create a 3 X 3 matrix with the values ranging from 5 to 10 (★☆☆).

code lines allowed = `1`

In [ ]:
np.random.randint(5,10+1, size=(3,3))

array([[ 7,  8, 10],
       [10,  8,  6],
       [ 6,  7,  8]])

#### 3. Create a 4 x 4 matrix with the `0` on the borders and `1` inside.(★☆☆)

code lines allowed = `2`

In [ ]:
t=np.random.randint(1,size=(4,4),)
t[1:3,1:3]=1
t

array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 0]])

In [ ]:
y=np.zeros((4,4))
y[1:-1,1:-1]=1
y

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

#### 4. Create matrix of ones of shape (5,5) but display/trim the lower half across the diagonal (★☆☆)

code lines allowed = `1`


In [ ]:
np.ones([5,5])[(1,2,2,3,3,3,4,4,4,4,4),(0,0,1,0,1,2,0,1,2,3,4)]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.tril(np.ones((5,5)))

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

#### 5. Create a 2D array of shape (10,10) with ones on the diagonal and zeros elsewhere (★☆☆)

code lines allowed = `1`

In [ ]:
np.eye(10,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### 6. Please create an immutable array of dimension 1D with size 10. Can you change the fifth element? (★★☆)

code lines allowed = `3`

In [ ]:
np.array(set([i for i in range(10)]))

array({0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, dtype=object)

In [ ]:
arr = np.ones(10)
arr.flags.writeable=False
arr[4]=10

ValueError: ignored

In [ ]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 7. Consider the row vector `r=[2,4,6,8,10]`, create a new row vector `rnew` such that four zeros are interleaved between each value in `r` (★★★)

code lines allowed = `4`

In [ ]:
r=[2,4,6,8,10] # rnew = [2,0,0,0,0,4,0,0,0,0,6,0,0,0,0,8,0,0,0,0,10]
rnew=np.array([0]) 
r*rnew

array([0, 0, 0, 0, 0])

In [ ]:
# rnew = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] 5/10
# indx_r = [0,1,2,3,4] * 5 3/10
# ind_rnew=[0,5,10,15,20]

In [ ]:
r = np.array(r)
rnew = np.zeros((4*4 + 5))
indx = np.arange(0,5)*5
rnew[indx]=r # rnew[[0,5,10,15,20]] = [2,4,6,8,10]
rnew

array([ 2.,  0.,  0.,  0.,  0.,  4.,  0.,  0.,  0.,  0.,  6.,  0.,  0.,
        0.,  0.,  8.,  0.,  0.,  0.,  0., 10.])

#### 8. (General question) Write a function, `howMany` that take a parameter `a` and returns the number of times you must multiply the digits in `a` such that only one digit remains.
example:
` howMany(729) Answer=3 because 7*2*9=126 (1) then 1*2*6=12 (2) then 1*2=2 (3)
`

In [ ]:
# def howMany(a):
#     return len(str(a))
  

In [ ]:
howMany(729)

3

In [ ]:
howMany(1024)

4

In [ ]:
def howMany(a): #hold counts=a=0 # z=split a # prod=np.prod(z) # len(str(prod)) != 1, a+=1  
   e = []
   for i in str(a):
       e.append(i)
   p = int(e[0])*int(e[1])*int(e[2])*int(3)
   return len(str(p))

In [ ]:
def howMany(a):
    times=0 if a <=9 else 1
    new_a = [int(i) for i in str(a)]
    prod = np.prod(new_a)
    while prod > 9:
        times+=1
        prod=np.prod([int(i) for i in str(prod)])
    return times

In [ ]:
howMany(0) # 1*0 = 0

1

In [ ]:
def howMany(a):
    times=0 if a <=9 else 1
    while True:
        prod=np.prod([int(i) for i in str(a)])
        if prod > 9:
            times+=1
            a = prod
        else: break
    return times

In [ ]:
howMany(197335799715397157317979539753931579)

2

Implement a difference function, which subtracts one list from another and returns the result.

It should remove all values from list `a`, which are present in list `b` keeping their order.

`diff([1,2],[1]) == [2]`

If a value is present in `b`, all of its occurrences must be removed from the other:

`diff([1,2,2,2,3],[2]) == [1,3]`

In [ ]:
def diff(a,b):
    pass

In [28]:
def arr_diff(a,b):
    return [i for i in a if i not in set(b)]


In [29]:
diff([1,2,2,2,3,3],[2])

[1, 3, 3]