<a href="https://colab.research.google.com/github/muga01/python_basics/blob/main/Exercise2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercise 2

In [2]:
import numpy as np

#### 1. Create a null vector of size 20 but fill the tenth value with 1 (★☆☆)

maximum number of code lines allowed = `2` 

In [3]:
x=np.empty(20) 
x[9]=1
x


array([4.67467929e-310, 1.73771270e+097, 9.82157975e+252, 8.89489936e+252,
       6.01346954e-154, 6.01347002e-154, 6.01347002e-154, 7.49877502e+247,
       6.96742172e+252, 1.00000000e+000, 1.19490107e+190, 5.08200698e+233,
       1.53336497e-094, 6.01347002e-154, 6.01347002e-154, 6.01347002e-154,
       1.88556770e+122, 4.96820036e+180, 6.80600993e+212, 8.73449626e-313])

#### 2. Create a 3 X 3 matrix with the values ranging from 5 to 10 (★☆☆).

code lines allowed = `1`

In [4]:
np.random.randint(5,10+1, size=(3,3))

array([[6, 6, 9],
       [6, 9, 9],
       [9, 8, 7]])

#### 3. Create a 4 x 4 matrix with the `0` on the borders and `1` inside.(★☆☆)

code lines allowed = `2`

In [5]:
t=np.random.randint(1,size=(4,4))
t[1:3,1:3]=1
t

array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 0]])

#### 4. Create matrix of ones of shape (5,5) but display/trim the lower half across the diagonal (★☆☆)

code lines allowed = `1`


In [6]:
a=np.ones([5,5])

#### 5. Create a 2D array of shape (10,10) with ones on the diagonal and zeros elsewhere (★☆☆)

code lines allowed = `1`

In [7]:
np.eye(10,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### 6. Please create an immutable array of dimension 1D with size 10. Can you change the fifth element? (★★☆)

code lines allowed = `3`

In [8]:
np.array(set([i for i in range(10)]))

array({0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, dtype=object)

#### 7. Consider the row vector `r=[2,4,6,8,10]`, create a new row vector `rnew` such that four zeros are interleaved between each value in `r` (★★★)

code lines allowed = `4`

In [9]:
r=[2,4,6,8,10]
rnew=np.array([0,0,0,0])
k*rnew

NameError: ignored

#### 8. (General question) Write a function, `howMany` that take a parameter `a` and returns the number of times you must multiply the digits in `a` such that only one digit remains.
example:
` howMany(729) Answer=3 because 7*2*9=126 (1) then 1*2*9=18 (2) then 1*8=8 (3)
`

In [ ]:
def howMany(a):
    return len(str(a))
  

In [ ]:
howMany(179)