# Numpy exercise 2

In [1]:
import numpy as np

#### 1. Create a null vector of size 20 but fill the tenth value with 1 (★☆☆)

maximum number of code lines allowed = `2` 

In [2]:
x=np.empty(20) 
x[10]=1
x



array([4.6372499e-310, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
       0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
       0.0000000e+000, 0.0000000e+000, 1.0000000e+000, 0.0000000e+000,
       0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
       0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000])

#### 2. Create a 3 X 3 matrix with the values ranging from 5 to 10 (★☆☆).

code lines allowed = `1`

In [3]:
np.random.randint(5,10+1, size=(3,3))

array([[ 9,  8,  9],
       [ 8,  6,  7],
       [10,  5,  8]])

#### 3. Create a 4 x 4 matrix with the `0` on the borders and `1` inside.(★☆☆)

code lines allowed = `2`

In [4]:
t=np.random.randint(1,size=(4,4))
t[1:3,1:3]=1
t



array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 0]])

#### 4. Create matrix of ones of shape (5,5) but display/trim the lower half across the diagonal (★☆☆)

code lines allowed = `1`


In [5]:
a=np.ones([5,5])


#### 5. Create a 2D array of shape (10,10) with ones on the diagonal and zeros elsewhere (★☆☆)

code lines allowed = `1`

In [6]:
np.eye(10,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### 6. Please create an immutable array of dimension 1D with size 10. Can you change the fifth element? (★★☆)

code lines allowed = `3`

In [7]:
np.array(set([i for i in range(10)]))


array({0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, dtype=object)

#### 7. Consider the row vector `r=[2,4,6,8,10]`, create a new row vector `rnew` such that four zeros are interleaved between each value in `r` (★★★)

code lines allowed = `4`

In [12]:
r=[2,4,6,8,10]
rnew=np.array([0,0,0,0])
k*rnew


array([0, 0, 0, 0])

#### 8. (General question) Write a function, `howMany` that take a parameter `a` and returns the number of times you must multiply the digits in `a` such that only one digit remains.
example:
` howMany(729) Answer=3 because 7*2*9=126 (1) then 1*2*9=18 (2) then 1*8=8 (3)
`

In [9]:
def howMany(a):
    return len(str(a))
  

In [10]:
howMany(179)

3