Create a 5X2 random integer array and Prints its attributes • The shape of an array • Array dimensions • The length of each elements of an array in bytes

In [88]:
import numpy as np
a = np.random.randint(0,10,size=(5,2))
np.shape(a)

(5, 2)

In [89]:
a.ndim

2

In [90]:
a.nbytes

80

Create a 4X2 random integer array from a range between 10 to 20 such that the difference between each element is 2.

In [91]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

Create a 6X4 random integer array and print the following

In [92]:
b= np.random.randint(10,size=(6,4))
b

array([[5, 7, 1, 6],
       [7, 4, 7, 4],
       [7, 5, 5, 4],
       [0, 3, 3, 0],
       [8, 5, 1, 7],
       [1, 4, 8, 2]])

• The third column

In [93]:
b[:,2]

array([1, 7, 5, 3, 1, 8])

• Array of odd rows and even columns

In [94]:
b[[1,3,5]]

array([[7, 4, 7, 4],
       [0, 3, 3, 0],
       [1, 4, 8, 2]])

In [95]:
b[:,[1,2,]]

array([[7, 1],
       [4, 7],
       [5, 5],
       [3, 3],
       [5, 1],
       [4, 8]])

• Array of square of each element

In [96]:
np.square(b)

array([[25, 49,  1, 36],
       [49, 16, 49, 16],
       [49, 25, 25, 16],
       [ 0,  9,  9,  0],
       [64, 25,  1, 49],
       [ 1, 16, 64,  4]])

Split the array into two equal sub arrays

In [97]:
np.split(b,b[2])

[array([[5, 7, 1, 6],
        [7, 4, 7, 4],
        [7, 5, 5, 4],
        [0, 3, 3, 0],
        [8, 5, 1, 7],
        [1, 4, 8, 2]]),
 array([], shape=(0, 4), dtype=int64),
 array([], shape=(0, 4), dtype=int64),
 array([], shape=(0, 4), dtype=int64),
 array([[8, 5, 1, 7],
        [1, 4, 8, 2]])]

• Sort the array by the second row

In [124]:
b[:,1].argsort()
b.sort()

• Sort the array by the second column

In [99]:
np.sort(b,axis= 1)

array([[1, 5, 6, 7],
       [4, 4, 7, 7],
       [4, 5, 5, 7],
       [0, 0, 3, 3],
       [1, 5, 7, 8],
       [1, 2, 4, 8]])

• Amax from axis 0 and Amin from axis 1

In [100]:
np.max(b,axis=0)

array([8, 7, 8, 7])

In [101]:
np.min(b,axis=0)

array([0, 3, 1, 0])

• Delete column 2 and insert [1,2,3,4,5,6] to column 2

In [60]:
np.delete(b,b[:,1])
b[:,1]= [1,2,3,4,5,6]
b

array([[0, 1, 1, 0],
       [3, 2, 6, 4],
       [4, 3, 0, 6],
       [2, 4, 0, 8],
       [3, 5, 0, 5],
       [3, 6, 3, 1]])

• Rotate by 90 degree

In [102]:
np.rot90(b)

array([[6, 4, 4, 0, 7, 2],
       [1, 7, 5, 3, 1, 8],
       [7, 4, 5, 3, 5, 4],
       [5, 7, 7, 0, 8, 1]])

• Print the most frequent value in the array

In [ ]:
print(np.bincount(b).argmax())

• Flatten the array to 1D

In [108]:
b.flatten()

array([5, 7, 1, 6, 7, 4, 7, 4, 7, 5, 5, 4, 0, 3, 3, 0, 8, 5, 1, 7, 1, 4,
       8, 2])

• Replace values less than 10 by a NAN.

In [ ]:
b[b < 10] = [np.nan]


 Summarize the array statistically (mean,mode,median, ¼ -quartile, ¾-quartile,max,min)

In [103]:
np.mean(b)

4.333333333333333

In [86]:
np.percentile(b, 0.75)

5.0

In [104]:
np.percentile(b, 3.75)

0.0

In [105]:
np.max(b)

8

In [106]:
np.min(b)

0