<a href="https://colab.research.google.com/github/muga01/python_basics/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NUMPY - NUMerical PYthon
# Array === list built function

In [ ]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
lst = [1,2,3,4,5]
lst+=lst
lst

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
# convert a list to an array and viceversa
lst = [1,2,3,4,5]
lst_converted = np.array(lst)

list(lst_converted+lst_converted)

[2, 4, 6, 8, 10]

In [ ]:
x = np.array([[i+j for i in range(5)] for j in range(6)])# 6 rows x 5 columns
x.shape
x.dtype

dtype('int64')

##### Creating numpy arrays from scratch
* `numpy.ones`
* `numpy.zeros`
* `numpy.random`
* `numpy.linspace`
* `numpy.arange`
* `numpy.eye`
* `numpy.reshape`

In [ ]:
# ones
np.ones(shape=(2,))
# zeros
np.zeros(10)
# linspace
x=np.linspace(10,20,20)
# arange==range
y=np.arange(10,20+1,5)

# Eye
z=np.eye(10,10)

# Reshape
p=x.reshape((5,2,2))


In [ ]:
# Random
k = np.arange(1,10+1,1)
np.random.random(5)
np.random.randint(1,10)
np.random.permutation(k).reshape((2,5))
np.random.uniform(20,25,size=(1000))
np.random.normal(loc=10,scale=0.5,size=(2,5))

array([[10.30275294, 10.03860843, 10.68777886, 10.60940989, 10.37367891],
       [10.52675579, 10.42195778, 10.19861264,  9.63494231,  9.61642078]])

In [ ]:
z = np.random.RandomState(seed=4500)

In [ ]:
z.randint(1,10,size=(2,5))

array([[4, 2, 9, 1, 2],
       [6, 5, 5, 2, 7]])

In [ ]:
q=np.random.randint(1,10,size=(1,),dtype='int32')
q

array([2], dtype=int32)

In [ ]:
q.itemsize
q.nbytes

4

In [ ]:
#empty
np.empty()

array([[4.65743038e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [ ]:
# size, shape, dimension,memory
p.size
np.prod(p.shape)
p.shape
#len(p)
len(p.shape)
p.ndim
p.itemsize * p.size
#p.nbytes

160

In [ ]:
m = np.ones(10)
len(m)
m.size

10

Indexing of arrays,
* Accessing single elements
* Accessing multiple elements

Slicing of arrays,Joining and splitting of arrays

In [ ]:
np.random.seed(50)
x1= np.random.randint(1,10, size=(5,))
x2= np.random.randint(1,20,size=(4,6))
x3 = np.random.randint(1,20,size=(2,4,2))

In [ ]:
x1[3] # 1D
x2[2,2] #2D
x1

array([1, 1, 2, 5, 7])

In [ ]:
# SLICING
y=x1[1:4]
#y[1] = 50
x1[::-1]
x1[::-2] #[2,1,1]

array([7, 2, 1])

In [ ]:
x2

array([[ 6,  7, 14,  6,  3,  8],
       [16,  5, 15,  4,  7, 12],
       [18, 11, 10,  1,  7,  3],
       [16, 10,  4,  3, 13,  1]])

In [ ]:
x2[:3,2:4]
x2[:,0]
x2[0,:]

array([ 6,  7, 14,  6,  3,  8])

In [ ]:
x1
print(x1.reshape((1,5))) # row vector
x1.reshape((5,1)) # column vector
print(x1[:,np.newaxis])

[[1 1 2 5 7]]
[[1]
 [1]
 [2]
 [5]
 [7]]


In [ ]:
x2

array([[ 6,  7, 14,  6,  3,  8],
       [16,  5, 15,  4,  7, 12],
       [18, 11, 10,  1,  7,  3],
       [16, 10,  4,  3, 13,  1]])

In [ ]:
# Join
x = np.random.randint(1,40,size=(10,))
y = np.random.randint(1,23,size=(10,))
print(f'{x}\n{y}')

[25 34 11 29 31 38 14 37  9 14]
[18 18 19 19 10  5 15 17  1 12]


In [ ]:
np.concatenate([x,y])
z=np.hstack((x,y))
p=np.vstack((x,y))
p=np.vstack((p,x))
p

array([[25, 34, 11, 29, 31, 38, 14, 37,  9, 14],
       [18, 18, 19, 19, 10,  5, 15, 17,  1, 12],
       [25, 34, 11, 29, 31, 38, 14, 37,  9, 14]])

In [ ]:
#split
np.hsplit(z,[len(z)//2])
np.vsplit(p,[1,2])

[array([[25, 34, 11, 29, 31, 38, 14, 37,  9, 14]]),
 array([[18, 18, 19, 19, 10,  5, 15, 17,  1, 12]]),
 array([[25, 34, 11, 29, 31, 38, 14, 37,  9, 14]])]

In [ ]:
q= np.random.randint(1,10, size=(4,5))
q

array([[5, 2, 7, 3, 4],
       [9, 3, 9, 2, 2],
       [1, 4, 8, 6, 6],
       [3, 4, 8, 1, 6]])

In [ ]:
np.vsplit(q,[1,2,3])

[array([[5, 2, 7, 3, 4]]),
 array([[9, 3, 9, 2, 2]]),
 array([[1, 4, 8, 6, 6]]),
 array([[3, 4, 8, 1, 6]])]

In [ ]:
#Computations-->Numpy

def calculate_reciprocal(array):
    return np.array([1/i for i in array])

In [ ]:
array=np.random.randint(1,5,6)
array

array([4, 2, 3, 2, 2, 3])

In [ ]:
calculate_reciprocal(array)

array([0.25      , 0.5       , 0.33333333, 0.5       , 0.5       ,
       0.33333333])

In [ ]:
array=np.random.randint(1,50,10000000)

In [ ]:

%timeit calculate_reciprocal(array)

1 loop, best of 5: 4.63 s per loop


In [ ]:
%timeit 1/array

10 loops, best of 5: 43.8 ms per loop


In [ ]:
4.63*1000/43.8

105.70776255707763

In [ ]:
#UFUNC
y**0.5
abs(y)
np.abs(y)

array([18, 18, 19, 19, 10,  5, 15, 17,  1, 12])

In [ ]:
#TRIG OPERATION
np.sin(np.pi)
np.cos(np.pi)
np.tan(np.pi/2)

1.633123935319537e+16

In [ ]:
theta = np.linspace(0,360,10)/np.pi
values= np.sin(theta)
print(f'{theta}\n{values}')

[  0.          12.73239545  25.46479089  38.19718634  50.92958179
  63.66197724  76.39437268  89.12676813 101.85916358 114.59155903]
[0.         0.16526316 0.32598142 0.47773486 0.61635013 0.73801516
 0.83938405 0.91766904 0.97071723 0.99706973]


In [ ]:
#Exponential plus logarithms
w=np.random.uniform(size=(10,))
print(w)
print(np.exp(w))

[0.22071446 0.0029063  0.3985406  0.35411417 0.2736726  0.00920407
 0.50412907 0.22945126 0.05906741 0.65047591]
[1.24696732 1.00291053 1.48964911 1.42491786 1.31478427 1.00924655
 1.65554303 1.25790956 1.06084675 1.91645267]


In [ ]:
np.exp2(w)

array([1.16531053, 1.00201653, 1.31817379, 1.27820051, 1.2088813 ,
       1.00640017, 1.41826691, 1.17238894, 1.04179211, 1.56968591])

In [ ]:
np.log(w)

array([-1.51088547, -5.8408736 , -0.91994592, -1.0381359 , -1.29582279,
       -4.68810995, -0.68492295, -1.47206464, -2.82907588, -0.43005102])

In [ ]:
np.log1p(w)

array([0.19943631, 0.00290209, 0.33542926, 0.30314749, 0.24190453,
       0.00916197, 0.40821404, 0.20656794, 0.05738872, 0.50106367])

In [ ]:
j=np.log1p(np.array([0,1,2,3,4]))
j

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [ ]:
np.expm1(j)

array([0., 1., 2., 3., 4.])

In [ ]:
mwaimu=[5]
mwaimu[0]

5

In [ ]:
## AGGREGATION
x=np.arange(10,20)
np.sum(x)

145

In [ ]:
np.add.reduce(x)
np.multiply.reduce(x)

335221286400

Write a function that takes in a string of one or more words, and returns the same string, but with all five or more letter words reversed (like the name of this kata).

Strings passed in will consist of only letters and spaces.
Spaces will be included only when more than one word is present.
Examples:

spinWords("Hey fellow warriors") => "Hey wollef sroirraw" 
spinWords("This is a test") => "This is a test" 
spinWords("This is another test") => "This is rehtona tes

In [ ]:
def spinWords(sentence):
    words = sentence.split(' ')
    newsentence = []
    for w in words:
        if len(w) >= 5:
            newsentence.append(w[::-1])
        else:
            newsentence.append(w)
    return ' '.join(newsentence)

In [ ]:
def spinWords(sentence):
    return ' '.join([w[::-1] if len(w) >= 5 else w for w in sentence.split(' ') ])

In [ ]:
spinWords("This is another test")

'This is rehtona test'

In [ ]:
spinWords("Hey fellow warriors")

'Hey wollef sroirraw'

In [ ]:
def spinWords(sentence):
    words = sentence.split(' ')
    x=[ l.append(i[::-1]) if len(i) >= 5 else l.append(i) for word in words]
    return sentence and ' '.join(l) [0/100]